spring:
  application:
    name: microservice-gateway-zuul-reg-exp
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
zuul:
  ignored-services: '*'
  routes:
    microservice-provider-user: /user/**

